// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glhflhqpsjlyrymquzsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsaGZsaHFwc2pseXJ5bXF1enNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDU2NzIsImV4cCI6MjA3MDU4MTY3Mn0.3SyI1bpqEPIi6IjQtcMNYpbFsdBWZ8ntxQwaj5Soe5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});